### ISSUE TITLE
Create a Google form for creating a dataset

### ISSUE THREAD

**Issue by andreskytt** [okestonia/opendata.riik.ee#425]
A form according to the yaml field (one resource per dataset). The results are submitted to GDocs sheet

**Comment by infokujur** [comment]
ENG https://docs.google.com/forms/d/1ZIBUHFfCLRKUIl1aj-YH96zpPKa7z95LhNbV83IdSa4
EST https://docs.google.com/forms/d/18Q0yAqz2fCAd03GAQzhDhGwSP4DdwS6fw0RoNqQ8h0M

Now it needs CTA button somewhere visible.

**Comment by keeganmcbride** [comment]
@infokujur @peepkungas where should these links go?

**Comment by infokujur** [comment]
Button > Lisa andmehulk / Add a Dataset
Next to "Alusta otsingut" button.

**Comment by keeganmcbride** [comment]
Finished with https://github.com/okestonia/opendata.riik.ee/commit/b1fc6a4ba10479a24e528258b1355305e007e1a1
