### ISSUE TITLE
Publish visitor numbers

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata.riik.ee#452]
GA stats etc

**Comment by keeganmcbride** [comment]
@infokujur we can do this, but I need access to GA. @peepkungas

**Comment by infokujur** [comment]
@peepkungas - we need Your input here. Please feel free tho share access to Keegan for publishing.

**Comment by keeganmcbride** [comment]
@peepkungas will make a dashboard and send me the embed code.

**Comment by keeganmcbride** [comment]
Added, but not sure if we should change how it is displayed.
