### ISSUE TITLE
Create application for making open data request possibilities more visible to the public

### ISSUE THREAD

**Issue by peepkungas** [okestonia/opendata.riik.ee#453]
Create application, which provides means to request open data sets from public organizations via URLs such as https://opendata.riik.ee/asutused/77000281-alutaguse-vallavalitsus. Use the same design layout as at  https://opendata.riik.ee/et/orgs/aegviidu-vallavalitsus/ . Expose the following data elements: organization name, registry code, address, postal code, nofollow link to business registry page for further details.

The application does no replace existing organization URLs at opendata.riik.ee such as https://opendata.riik.ee/et/orgs/aegviidu-vallavalitsus/. However, at certain moment of time URL's such as https://opendata.riik.ee/et/orgs/aegviidu-vallavalitsus/ should be redirected to the new application.

The pages MUST have Lighthouse Score at least 95 for mobile and desktop performance according to PageSpeed Insights (https://developers.google.com/speed/pagespeed/insights/).

HTML title and h1 heading follows the pattern "<organization name> - küsi andmeid" such as "Alutaguse Vallavalitus - küsi andmeid".

**Comment by keeganmcbride** [comment]
I don't really understand what you're asking here. It is a separate application, or you want me to do something on the current open data portal?

**Comment by keeganmcbride** [comment]
Should be done now?
