### ISSUE TITLE
Populate application with public organization data

### ISSUE THREAD

**Issue by peepkungas** [okestonia/opendata.riik.ee#454]
Create organization page for all organizations with registration codes starting with 7 (e.g. "77000281") from https://opendata.riik.ee/andmehulgad/ariregister/ dataset using the following attributes:
Organization name ("nimi"), registry code ("ariregistri_kood"), address ("ads_normaliseeritud_taisaadress"), postal code ("indeks_ettevotja_aadressis"), nofollow link to business registry ("teabesysteemi_link")

Input CSV example
nimi;ariregistri_kood;kmkr_nr;ettevotja_staatus;ettevotja_staatus_tekstina;ettevotja_aadress;asukoht_ettevotja_aadressis;asukoha_ehak_kood;asukoha_ehak_tekstina;indeks_ettevotja_aadressis;ads_adr_id;ads_ads_oid;ads_normaliseeritud_taisaadress;teabesysteemi_link
Alutaguse Vallavalitsus;77000281;;R;Registrisse kantud;;Tartu mnt 56;2025;Iisaku alevik, Alutaguse vald, Ida-Viru maakond;41101;3294475;;Ida-Viru maakond, Alutaguse vald, Iisaku alevik, Tartu mnt 56;https://ariregister.rik.ee/ettevotja.py?ark=77000281&ref=rekvisiidid

**Comment by keeganmcbride** [comment]
This will take a bit of time to investigate how to best do it / what impact a large increase in organizations will do to the site. Needs to be a bit more clear how we should display also organizations with 0 datasets added.

**Comment by keeganmcbride** [comment]
Done with https://github.com/okestonia/opendata.riik.ee/commit/0a3a54bdbaa1e6b3614a96687c18b193561b017e
