### ISSUE TITLE
Generate sitemap for all application URLs

### ISSUE THREAD

**Issue by peepkungas** [okestonia/opendata.riik.ee#455]
Generate sitemap(s) for all URLs and publish the URLs at https://opendata.riik.ee/sitemaps/
If there are 50k or more records, then split URLs into different sitemaps each having less then 50k records.

**Comment by keeganmcbride** [comment]
https://opendata.riik.ee/sitemap.xml

**Comment by peepkungas** [comment]
The scope of the task is to generate separate sitemap for URLs created in the context of https://github.com/okestonia/opendata.riik.ee/issues/454 .

**Comment by keeganmcbride** [comment]
We should discuss this in more detail, i am still confused by what is wanted here.

**Comment by peepkungas** [comment]
https://opendata.riik.ee/sitemap.xml includes all necessary files
