### ISSUE TITLE
Add page description to organization pages

### ISSUE THREAD

**Issue by peepkungas** [okestonia/opendata.riik.ee#459]
Add the following description to each organization page:

Avaliku teabe seadus kohustab teabevaldajaid tegema andmekogudes sisalduvad juurdepääsupiiranguta andmed kättesaadavaks avaandmetena. Siin lehel saad esitada tellimuse asutuse <organization name in bold> avaandmete avalikustamiseks. Avaandmete tellimuse vaatab üle ja aitab täide viia Open Knowledge Estonia koos Majandus- ja kommunikatsiooniministeeriumiga.

Add the following as meta description: "Siit saad tellida asutuse <organization name> avaandmeid."

**Comment by keeganmcbride** [comment]
Can you tell me where it should go on the organization page?

**Comment by keeganmcbride** [comment]
@peepkungas where on the page do you want this to go?

**Comment by keeganmcbride** [comment]
Done with https://github.com/okestonia/opendata.riik.ee/commit/0a3a54bdbaa1e6b3614a96687c18b193561b017e
