### ISSUE TITLE
Add Statistics Estonia dashboards to Apps listing

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata.riik.ee#461]

**Comment by keeganmcbride** [comment]
I need more information here. Which app?

**Comment by infokujur** [comment]
They have different things here: https://www.stat.ee/261715
Also all Shiny work, what is using open data.

**Comment by keeganmcbride** [comment]
@infokujur there are many applications here, do you want every application to go up, or should we just link to stat ee?

**Comment by infokujur** [comment]
Lets separate local stuff what is using OD and leave out Eurostat publications.

**Comment by keeganmcbride** [comment]
I added in the main local ones I could find with commit: https://github.com/okestonia/opendata.riik.ee/commit/b7c8713fa72ffec9dd9af45d328c23aa4a6d4ce6

**Comment by keeganmcbride** [comment]
@infokujur Please let me know if any other apps should be added, if not, then please close issue.

**Comment by infokujur** [comment]
Yes, let it be that way. There are more stuff but from EU level, what we leave out atm. But if we need to show more, what is done with EE statistics we add. (Ideal word it should be automated/solved when Stats will integrate)
