### ISSUE TITLE
Add Tõetamm to apps

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata.riik.ee#464]
https://tamm.stat.ee/

**Comment by tkutsar** [comment]
Does it have an official title in English as well or shall I just go with the dramatic "The Oak of Truth"?

**Comment by infokujur** [comment]
Some native speaker could help out :).

**Comment by keeganmcbride** [comment]
Oak of truth or Tree of Truth is what I have seen used in official communications.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tkutsar** [comment]
Added.
