### ISSUE TITLE
Add resource Keskvalitsuse asutused haldusalade kaupa

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata.riik.ee#467]
https://www.rahandusministeerium.ee/sites/default/files/keskvalitsuse_asutused_haldusalade_kaupa.xlsx

**Comment by tkutsar** [comment]
I need a bit more information about this dataset:

1. Is it maintained by Rahandusministeerium? Or which organization?
2. Is there a description available somewhere?
3. Any information about update frequencies, maintainer contacts etc. ?

**Comment by infokujur** [comment]
Yes. All the info here: https://www.rahandusministeerium.ee/et/riigihaldus

**Comment by tkutsar** [comment]
https://opendata.riik.ee/andmehulgad/keskvalitsuse-asutused/
