### ISSUE TITLE
Add EDP Analytical Report 9: The Economic Benefits of Open Data

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata.riik.ee#475]
https://www.europeandataportal.eu/sites/default/files/analytical_report_n9_economic_benefits_of_open_data.pdf

**Comment by infokujur** [comment]
About on siin: https://www.europeandataportal.eu/en/highlights/open-data-maturity-report-2019-out-now

**Comment by tkutsar** [comment]
Lisatud:

https://opendata.riik.ee/sundmused-ja-infomaterjalid/
