### ISSUE TITLE
Add 25.11.2019 töögrupi kohtumise materjal

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata.riik.ee#477]
https://docs.google.com/document/d/18ymXTDj2TEiiZCupuM_svfmhbpUvtAgsGc4ibepzJrg

https://docs.google.com/presentation/d/11E9nFeIJ6Mxj-Q7ryhZVBLWJQQPR2FYdChjABFJ9XWY

**Comment by tkutsar** [comment]
Added.
