### ISSUE TITLE
Add Terviserajad to Apps

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata.riik.ee#478]
https://terviserajad.crabsec.ee/

**Comment by keeganmcbride** [comment]
Added with: https://github.com/okestonia/opendata.riik.ee/commit/8ec27e466728c5cbf0166210354c9a5b947d2497

Will need the description in Estonian though.

**Comment by tkutsar** [comment]
E-mail to author sent regarding the description.

**Comment by infokujur** [comment]
Lisatud
