### ISSUE TITLE
Add open data related News to blog 

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata.riik.ee#529]
https://e-estonia.com/hans-ai-support-tool-for-estonian-parliament/?fbclid=IwAR07wHULUrXH33_pE8xxG_l9l6k22NX0cmyTXmpl9YkEdqjsp6KEWcNk6OA

**Comment by tkutsar** [comment]
Kas lisan ainult ingliskeelse versiooni?

**Comment by infokujur** [comment]
Kui on, mõlemad.

**Comment by tkutsar** [comment]
https://opendata.riik.ee/en/blogi/introducing-hans/
