### ISSUE TITLE
New functionality: adding new organisations via the portal

### ISSUE THREAD

**Issue by SigritSiht** [okestonia/opendata.riik.ee#624]
Currently it is not possible to add new organisations via the portal and users must therefore have GitHub accounts and do it via Github. This is not very user-friendly, especially when we want even more and diverse organisations to share their data in the portal.

**Comment by SigritSiht** [comment]
> Currently it is not possible to add new organisations via the portal and users must therefore have GitHub accounts and do it via Github. This is not very user-friendly, especially when we want even more and diverse organisations to share their data in the portal.

Priority of this issue is not as high as priority of issue Split collections into separate entries #589.

**Comment by peepkungas** [comment]
This functionality seems to overlap with the functionality of the new portal. Is it still relevant?
