### ISSUE TITLE
Add töögrupi kohtumise kokkuvõte 

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata.riik.ee#905]
Kokkuvõte siin: https://docs.google.com/document/d/1yY1ydJKV56wZk3Dm1xRwnDqjE14fdtsRz8L9FJBeL8s

Esitlused siin: 
[Avaandmete töögrupp 23032020(1).pptx](https://github.com/okestonia/opendata.riik.ee/files/4599078/Avaandmete.toogrupp.23032020.1.pptx)
[Avatud teaduse raamistik Eestis ja PSI (23. märts 2020; Martin Eessalu)(1)(1).pdf](https://github.com/okestonia/opendata.riik.ee/files/4599080/Avatud.teaduse.raamistik.Eestis.ja.PSI.23.marts.2020.Martin.Eessalu.1.1.pdf)
[ODPSI_23.03_ST(1).pptx](https://github.com/okestonia/opendata.riik.ee/files/4599082/ODPSI_23.03_ST.1.pptx)

**Comment by tkutsar** [comment]
Added with PR:

https://github.com/okestonia/opendata.riik.ee/pull/908

**Comment by infokujur** [comment]
Ei näe siin https://opendata.riik.ee/blogi/

**Comment by infokujur** [comment]
Materjal on üleval siin https://opendata.riik.ee/sundmused-ja-infomaterjalid/
Aga oleks hea välja näidata ka blogi osas.

**Comment by tkutsar** [comment]
Lisatud PR lühikese blogipostitusega, mis juhib infomaterjalide lehele.

https://github.com/okestonia/opendata.riik.ee/pull/1012

**Comment by tkutsar** [comment]
https://opendata.riik.ee/et/blogi/tooruhma-kohtumine/

Panen kinni.
