### ISSUE TITLE
Add additional info to the home page

### ISSUE THREAD

**Issue by SigritSiht** [okestonia/opendata.riik.ee#931]
There seems to be a common misunderstanding among some organisations that instead of linking their data from their server they add data to our servers. To make it clearer for all it is better to add additional info about it to the home page: "Teabevaldajad lisavad avaandmete portaali lingi oma andmekogule, et suurendada andmekogu kasutust ning kõlapinda."

**Comment by keeganmcbride** [comment]
Can you explain a bit more what you mean, I am not sure I understand what the issue is here.

**Comment by SigritSiht** [comment]
The portal is in essence a portal for link where organisations link their data resources but it doesn't read so to them, they see the home page and it doesn't specify enoguh that there is no extra work involved for the orgs to duplicate the data itself but that just adding a link and metadata is enoguh.

**Comment by keeganmcbride** [comment]
Ah okay, understood. Where do you want the extra info on the home page to go?
