### ISSUE TITLE
Add new guideline materials

### ISSUE THREAD

**Issue by SigritSiht** [okestonia/opendata.riik.ee#968]
Avaandmete loomise juhend: https://docs.google.com/document/d/12QSazJeg8SXkqnJki5S3Ak9j9-XEJndoT-6wSdwNEsQ/edit?usp=sharing
Soovitused avaandmete mõju hindamiseks organisatsioonis: https://docs.google.com/document/d/1OETr83_KwGmYV7aKLcRyiWY1kIgsdDZIqfb0getIjOM/edit?usp=sharing

**Comment by tkutsar** [comment]
PR created: https://github.com/okestonia/opendata.riik.ee/pull/969
